### PR TITLE
fix(swatch-palette): update palette with colors package

### LINKED ISSUE #326: Update color palette specifications component to use v2 colors
https://www.ibm.com/design/language/elements/color/#specifications

The `SwatchPalette` component on the Color page needs to get updated to show the [v2 colors](https://github.com/carbon-design-system/carbon/tree/master/packages/colors). Ideally this would pull directly from the colors package instead of using the hardcoded values. (depending on complexity could be a future enhancement)

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #326 

Updates swatch palette to v2 colors

**New**
- added `color-convert` package 
- added `@carbon/colors` package

**Changed**
- `SwatchPalette` to use `@carbon/colors` [variables](https://github.com/carbon-design-system/carbon/blob/master/packages/colors/src/colors.js) instead of hard coding HEX and CMYK values
- update coolGray and Gray PMS values

**To-do:**
- [x] ~Update Grays PMS values~

**Testing/Reviewing:**
- [ ] check that HEX values are updated to the correct values 
    - [IBM_Colors_RGB_HEX_V02_REFERENCE.pdf](https://github.com/carbon-design-system/design-language-website/files/3768805/IBM_Colors_RGB_HEX_V02_REFERENCE.pdf)
- [ ] check that RBG and CMYK colors are converted properly from the HEX value
    - can use color converter [tool](https://www.w3schools.com/colors/colors_converter.asp) for CMYK
    - _Note: I think the CMYK values in the [IBM_Colors_CMYK_V02_REFERENCE.pdf](https://github.com/carbon-design-system/design-language-website/files/3768864/IBM_Colors_CMYK_V02_REFERENCE.pdf) are outdated. All the color conversion tools I used to check the correct values don't match what the pdf shows_ 🤔
- [ ]  check that PMS values for the Grays are correct
    - [IBM_Colors_PANTONE_V02_REFERENCE.pdf](https://github.com/carbon-design-system/design-language-website/files/3768796/IBM_Colors_PANTONE_V02_REFERENCE.pdf)

### CODE REVIEW

**Comment by jnm2377** [comment]
fyi @sadekbazaraa 👀 For some reason I couldn't request your review

**Comment by sadekbazaraa** [comment]
Thanks @jnm2377 I just reviewed and this all looks right to me!!

**Comment by alisonjoseph** [comment]
FYI @sadekbazaraa @lisalind-ibm

**Comment by mjabbink** [comment]
If @sadek has checked hex, rgb, Pantone and CMYK I’m good.

File: src/components/SwatchPaletteWidget/SwatchPalette.js [hunk 1]
```diff
@@ -1,556 +1,598 @@
...
+      letterNum = `y${stringNum}`;
+    } else {
+      letterNum = `k${stringNum}`;
+    }
+    return letterNum;
+  });
+
+  // converts cmyk array to one string
+  const cmykString = stringCmykArr.join(' ');
+  return cmykString;
```
Comment (joshblack) [inline src/components/SwatchPaletteWidget/SwatchPalette.js]: Would it make sense to do the following since the indices are known? Could get rid of the call to `map` above as a result

```suggestion
  return [
    `c${convertedHex[0]}`,
    `m${convertedHex[1]}`,
    `y${convertedHex[2]}`,
    `k${convertedHex[3]}`,
  ].join(' ');
```

File: src/components/SwatchPaletteWidget/SwatchPalette.js [hunk 2]
```diff
@@ -1,556 +1,598 @@
...
+};
+
 const PALETTES = {
   black: {
     '100': {
-      hex: '#000000',
+      hex: `${black}`,
```
Comment (joshblack) [inline src/components/SwatchPaletteWidget/SwatchPalette.js]: Would this also work?

```suggestion
      hex: black,
```

File: src/components/SwatchPaletteWidget/SwatchPalette.js [hunk 3]
```diff
@@ -1,556 +1,598 @@
...
       pms: 'Black 6',
-      cmyk: 'c75 m68 y67 k90',
+      cmyk: convertToCmyk(`${black}`),
```
Comment (joshblack) [inline src/components/SwatchPaletteWidget/SwatchPalette.js]: Would this work?

```suggestion
      cmyk: convertToCmyk(black),
```

**Comment by jnm2377** [comment]
> Should we be converting to the pantone system as well as opposed to hardcoding them?

@vince I'm not entirely sure how this would be done. I'm not familiar with the pantone system, and I haven't seen a conversion for it in any color conversion tools I've looked at. More importantly, would it be possible to even convert? Some of the PMS values aren't numbers, they're names like `Cool Gray 11`, `Warm Gray 9` etc. Again, I'm not familiar enough with pantone to know why some have numerical values and some have names.

**Comment by sadekbazaraa** [comment]
All of these Pantone colors were hand selected. Any sort of conversion algorithm from RGB or CMYK would not be suitable in this case.

**Comment by vpicone** [comment]
@sadekbazaraa how do we handle changes to the palletes then? Does someone need to go and re-pick the pantone colors?

**Comment by jnm2377** [comment]
@vpicone not sure what you mean. I've updated the PMS values that needed to be updated. I used the v2 color palette PDFs (linked in the PR description) to get the correct values.

**Comment by sadekbazaraa** [comment]
@vpicone the PMS and CMYK colors did not change from V1 to V2 so we're all good there

**Comment by vpicone** [comment]
@sadekbazaraa @jnm2377 sorry I might be turned around. Did the PMS colors change in v2?

I was under the impression these different formats (hex, cmyk, Pantone) we’re all essentially trying to “describe” the same color. I’m confused how one of them could be updated on a color without updating the others.

**Comment by sadekbazaraa** [comment]
@vpicone it's a valid question! The changes are so marginal across RGB that these changes have a negligible affect to the Pantone and CMYK colors. We'd have to have a much more significant departure to reach a meaningful threshold were the changes would be perceptible in print. Does that make sense? Hence why the only changes were to RGB/HEX.

**Comment by vpicone** [comment]
@sadekbazaraa that makes sense, thanks for the clarification!

**Comment by vpicone** [comment]
@sadekbazaraa this PR also makes it so we compute cmyk from the hex values. So if hex updates, cmyk would as well. Is that not expected?

**Comment by jnm2377** [comment]
@sadekbazaraa just to clarify, the only colors that were hand selected and wouldn't have changed in v2 are the PMS colors? We are using the colors package to generate the hex code, and then rather than hard coding the CMYK colors like before, we are converting the hex to CMYK, so that they are always up to date with the latest colors package (which means that the CMYK colors changed as well). The RGB colors were already generated from the hex code, so those also changed. Is that ok? cc: @vpicone

**Comment by sadekbazaraa** [comment]
@vpicone because there's so much variation in the way that conversions take place, we prefer to use Adobe's engine for those conversions. In efforts to try and minimize unnecessary palette updates and given that the CMYK changes would be negligible compared to the RGB changes from V1 to V2, we've decided to leave the CMYK and PMS values as they were in V1. It's highly unlikely that we'll change the CMYK values unless we find the budget to do an extensive offset printing to test to further dial in the CMYK values. Let me know if all this makes sense.

**Comment by sadekbazaraa** [comment]
@vpicone The single source of truth is the .zip package generated by Lisa Lind and team. All of the .ase and reference PDF files are there, so as long as what we have on our sites matches that source then we should be good.

**Comment by alisonjoseph** [comment]
> In efforts to try and minimize unnecessary palette updates and given that the CMYK changes would be negligible compared to the RGB changes from V1 to V2, we've decided to leave the CMYK and PMS values as they were in V1. It's highly unlikely that we'll change the CMYK values unless we find the budget to do an extensive offset printing to test to further dial in the CMYK values.

Given this comment, it seems the conversion to cmyk should be removed/reverted? and we should just leave the hardcoded values for now since those aren't stored in code currently. thoughts?

**Comment by jnm2377** [comment]
@sadekbazaraa did the CMYK colors not change in v2? I am generating them from the new hex code, so in this PR the CMYK reflects what the hex code color is. Should we move back to hard coding them in that case, so that they're not converted from the hex code?

**Comment by jnm2377** [comment]
@alisonjoseph thanks for the clarification. I wasn't sure if CMYK had also changed. Will update the PR.

**Comment by sadekbazaraa** [comment]
@jnm2377 The CMYK and PANTONE values are the same in V1. It's just the RGB values that changed (very slightly) to gain a few more degrees of accessibility. We need to hard code the CMYK values either way and should not rely on algorithms to do the conversion which will always give different results depending on the engine and math of the conversion. The CMYK values have been individually set and adjusted through several other means.

File: src/components/SwatchPaletteWidget/SwatchPalette.js [hunk 4]
```diff
@@ -1,554 +1,570 @@
...
 const { prefix } = settings;
 
 const PALETTES = {
   black: {
     '100': {
-      hex: '#000000',
+      hex: black,
       pms: 'Black 6',
-      cmyk: 'c75 m68 y67 k90',
+      cmyk: 'c60 m40 y40 k100',
```
Comment (jnm2377) [inline src/components/SwatchPaletteWidget/SwatchPalette.js]: Reverted the CMYK colors according to the pdf values. The PDF has a different value for black than it did before. The rest of the colors remain the same, however.
Screen Shot 2019-11-05 at 3 18 41 PM

File: src/components/SwatchPaletteWidget/SwatchPalette.js [hunk 5]
```diff
@@ -1,554 +1,570 @@
...
-      pms: '537',
+      hex: gray[30],
+      pms: 'Cool Gray 3',
       cmyk: 'c27 m18 y15 k0',
     },
     '40': {
-      hex: '#A4A4A4',
-      pms: '2162',
+      hex: gray[40],
+      pms: 'Cool Gray 4',
```
Comment (vpicone) [inline src/components/SwatchPaletteWidget/SwatchPalette.js]: It looks like some of these got swapped or something? Is it supposed to be an integer?
